/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as MemoryGuideRouteImport } from './routes/memory-guide'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDeliveryRouteImport } from './routes/_authenticated/delivery'
import { Route as AuthenticatedEditingRouteImport } from './routes/_authenticated/editing'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedGuideReviewsRouteImport } from './routes/_authenticated/guide-reviews'
import { Route as AuthenticatedHeirloomRouteImport } from './routes/_authenticated/heirloom'
import { Route as AuthenticatedKpiRouteImport } from './routes/_authenticated/kpi'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMarketingHubRouteImport } from './routes/_authenticated/marketing-hub'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPixiesetRouteImport } from './routes/_authenticated/pixieset'
import { Route as AuthenticatedPostProductionRouteImport } from './routes/_authenticated/post-production'
import { Route as AuthenticatedPrepRouteImport } from './routes/_authenticated/prep'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedQuoteRouteImport } from './routes/_authenticated/quote'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated/sops'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as FTokenRouteImport } from './routes/f/$token'
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads_.$leadId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryGuideRoute = MemoryGuideRouteImport.update({
  id: '/memory-guide',
  path: '/memory-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryRoute = AuthenticatedDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditingRoute = AuthenticatedEditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideReviewsRoute =
  AuthenticatedGuideReviewsRouteImport.update({
    id: '/guide-reviews',
    path: '/guide-reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeirloomRoute = AuthenticatedHeirloomRouteImport.update({
  id: '/heirloom',
  path: '/heirloom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKpiRoute = AuthenticatedKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingHubRoute =
  AuthenticatedMarketingHubRouteImport.update({
    id: '/marketing-hub',
    path: '/marketing-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPixiesetRoute = AuthenticatedPixiesetRouteImport.update({
  id: '/pixieset',
  path: '/pixieset',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPostProductionRoute =
  AuthenticatedPostProductionRouteImport.update({
    id: '/post-production',
    path: '/post-production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrepRoute = AuthenticatedPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuoteRoute = AuthenticatedQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FTokenRoute = FTokenRouteImport.update({
  id: '/f/$token',
  path: '/f/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/leads_/$leadId',
    path: '/leads/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/memory-guide': typeof MemoryGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/editing': typeof AuthenticatedEditingRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/guide-reviews': typeof AuthenticatedGuideReviewsRoute
  '/heirloom': typeof AuthenticatedHeirloomRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/pixieset': typeof AuthenticatedPixiesetRoute
  '/post-production': typeof AuthenticatedPostProductionRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/production': typeof AuthenticatedProductionRoute
  '/quote': typeof AuthenticatedQuoteRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/f/$token': typeof FTokenRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/memory-guide': typeof MemoryGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/delivery': typeof AuthenticatedDeliveryRoute
  '/editing': typeof AuthenticatedEditingRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/guide-reviews': typeof AuthenticatedGuideReviewsRoute
  '/heirloom': typeof AuthenticatedHeirloomRoute
  '/kpi': typeof AuthenticatedKpiRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/pixieset': typeof AuthenticatedPixiesetRoute
  '/post-production': typeof AuthenticatedPostProductionRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/production': typeof AuthenticatedProductionRoute
  '/quote': typeof AuthenticatedQuoteRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/f/$token': typeof FTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/memory-guide': typeof MemoryGuideRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/delivery': typeof AuthenticatedDeliveryRoute
  '/_authenticated/editing': typeof AuthenticatedEditingRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/guide-reviews': typeof AuthenticatedGuideReviewsRoute
  '/_authenticated/heirloom': typeof AuthenticatedHeirloomRoute
  '/_authenticated/kpi': typeof AuthenticatedKpiRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/marketing-hub': typeof AuthenticatedMarketingHubRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/pixieset': typeof AuthenticatedPixiesetRoute
  '/_authenticated/post-production': typeof AuthenticatedPostProductionRoute
  '/_authenticated/prep': typeof AuthenticatedPrepRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/quote': typeof AuthenticatedQuoteRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sops': typeof AuthenticatedSopsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/f/$token': typeof FTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leads_/$leadId': typeof AuthenticatedLeadsLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/memory-guide'
    | '/admin'
    | '/bookings'
    | '/clients'
    | '/delivery'
    | '/editing'
    | '/governance'
    | '/guide-reviews'
    | '/heirloom'
    | '/kpi'
    | '/leads'
    | '/marketing'
    | '/marketing-hub'
    | '/memory'
    | '/packages'
    | '/pipeline'
    | '/pixieset'
    | '/post-production'
    | '/prep'
    | '/privacy'
    | '/production'
    | '/quote'
    | '/reports'
    | '/reviews'
    | '/safety'
    | '/sales'
    | '/settings'
    | '/sops'
    | '/tasks'
    | '/team'
    | '/training'
    | '/whatsapp'
    | '/f/$token'
    | '/leads/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/change-password'
    | '/memory-guide'
    | '/admin'
    | '/bookings'
    | '/clients'
    | '/delivery'
    | '/editing'
    | '/governance'
    | '/guide-reviews'
    | '/heirloom'
    | '/kpi'
    | '/leads'
    | '/marketing'
    | '/marketing-hub'
    | '/memory'
    | '/packages'
    | '/pipeline'
    | '/pixieset'
    | '/post-production'
    | '/prep'
    | '/privacy'
    | '/production'
    | '/quote'
    | '/reports'
    | '/reviews'
    | '/safety'
    | '/sales'
    | '/settings'
    | '/sops'
    | '/tasks'
    | '/team'
    | '/training'
    | '/whatsapp'
    | '/f/$token'
    | '/'
    | '/leads/$leadId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/memory-guide'
    | '/_authenticated/admin'
    | '/_authenticated/bookings'
    | '/_authenticated/clients'
    | '/_authenticated/delivery'
    | '/_authenticated/editing'
    | '/_authenticated/governance'
    | '/_authenticated/guide-reviews'
    | '/_authenticated/heirloom'
    | '/_authenticated/kpi'
    | '/_authenticated/leads'
    | '/_authenticated/marketing'
    | '/_authenticated/marketing-hub'
    | '/_authenticated/memory'
    | '/_authenticated/packages'
    | '/_authenticated/pipeline'
    | '/_authenticated/pixieset'
    | '/_authenticated/post-production'
    | '/_authenticated/prep'
    | '/_authenticated/privacy'
    | '/_authenticated/production'
    | '/_authenticated/quote'
    | '/_authenticated/reports'
    | '/_authenticated/reviews'
    | '/_authenticated/safety'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/sops'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/training'
    | '/_authenticated/whatsapp'
    | '/f/$token'
    | '/_authenticated/'
    | '/_authenticated/leads_/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  MemoryGuideRoute: typeof MemoryGuideRoute
  FTokenRoute: typeof FTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-guide': {
      id: '/memory-guide'
      path: '/memory-guide'
      fullPath: '/memory-guide'
      preLoaderRoute: typeof MemoryGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery': {
      id: '/_authenticated/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthenticatedDeliveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editing': {
      id: '/_authenticated/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof AuthenticatedEditingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide-reviews': {
      id: '/_authenticated/guide-reviews'
      path: '/guide-reviews'
      fullPath: '/guide-reviews'
      preLoaderRoute: typeof AuthenticatedGuideReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heirloom': {
      id: '/_authenticated/heirloom'
      path: '/heirloom'
      fullPath: '/heirloom'
      preLoaderRoute: typeof AuthenticatedHeirloomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpi': {
      id: '/_authenticated/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof AuthenticatedKpiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing-hub': {
      id: '/_authenticated/marketing-hub'
      path: '/marketing-hub'
      fullPath: '/marketing-hub'
      preLoaderRoute: typeof AuthenticatedMarketingHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pixieset': {
      id: '/_authenticated/pixieset'
      path: '/pixieset'
      fullPath: '/pixieset'
      preLoaderRoute: typeof AuthenticatedPixiesetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-production': {
      id: '/_authenticated/post-production'
      path: '/post-production'
      fullPath: '/post-production'
      preLoaderRoute: typeof AuthenticatedPostProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep': {
      id: '/_authenticated/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof AuthenticatedPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quote': {
      id: '/_authenticated/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof AuthenticatedQuoteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/f/$token': {
      id: '/f/$token'
      path: '/f/$token'
      fullPath: '/f/$token'
      preLoaderRoute: typeof FTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leads_/$leadId': {
      id: '/_authenticated/leads_/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDeliveryRoute: typeof AuthenticatedDeliveryRoute
  AuthenticatedEditingRoute: typeof AuthenticatedEditingRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedGuideReviewsRoute: typeof AuthenticatedGuideReviewsRoute
  AuthenticatedHeirloomRoute: typeof AuthenticatedHeirloomRoute
  AuthenticatedKpiRoute: typeof AuthenticatedKpiRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMarketingHubRoute: typeof AuthenticatedMarketingHubRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPixiesetRoute: typeof AuthenticatedPixiesetRoute
  AuthenticatedPostProductionRoute: typeof AuthenticatedPostProductionRoute
  AuthenticatedPrepRoute: typeof AuthenticatedPrepRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedQuoteRoute: typeof AuthenticatedQuoteRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDeliveryRoute: AuthenticatedDeliveryRoute,
  AuthenticatedEditingRoute: AuthenticatedEditingRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedGuideReviewsRoute: AuthenticatedGuideReviewsRoute,
  AuthenticatedHeirloomRoute: AuthenticatedHeirloomRoute,
  AuthenticatedKpiRoute: AuthenticatedKpiRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMarketingHubRoute: AuthenticatedMarketingHubRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPixiesetRoute: AuthenticatedPixiesetRoute,
  AuthenticatedPostProductionRoute: AuthenticatedPostProductionRoute,
  AuthenticatedPrepRoute: AuthenticatedPrepRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedQuoteRoute: AuthenticatedQuoteRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSopsRoute: AuthenticatedSopsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  MemoryGuideRoute: MemoryGuideRoute,
  FTokenRoute: FTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
