/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SopsRouteImport } from './routes/sops'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as PixiesetRouteImport } from './routes/pixieset'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as HeirloomRouteImport } from './routes/heirloom'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsRoute = SopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const PixiesetRoute = PixiesetRouteImport.update({
  id: '/pixieset',
  path: '/pixieset',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const HeirloomRoute = HeirloomRouteImport.update({
  id: '/heirloom',
  path: '/heirloom',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/editing': typeof EditingRoute
  '/governance': typeof GovernanceRoute
  '/heirloom': typeof HeirloomRoute
  '/kpi': typeof KpiRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/memory': typeof MemoryRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/pixieset': typeof PixiesetRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/safety': typeof SafetyRoute
  '/sops': typeof SopsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/editing': typeof EditingRoute
  '/governance': typeof GovernanceRoute
  '/heirloom': typeof HeirloomRoute
  '/kpi': typeof KpiRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/memory': typeof MemoryRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/pixieset': typeof PixiesetRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/safety': typeof SafetyRoute
  '/sops': typeof SopsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/clients': typeof ClientsRoute
  '/editing': typeof EditingRoute
  '/governance': typeof GovernanceRoute
  '/heirloom': typeof HeirloomRoute
  '/kpi': typeof KpiRoute
  '/leads': typeof LeadsRoute
  '/marketing': typeof MarketingRoute
  '/memory': typeof MemoryRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/pixieset': typeof PixiesetRoute
  '/prep': typeof PrepRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reports': typeof ReportsRoute
  '/reviews': typeof ReviewsRoute
  '/safety': typeof SafetyRoute
  '/sops': typeof SopsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/clients'
    | '/editing'
    | '/governance'
    | '/heirloom'
    | '/kpi'
    | '/leads'
    | '/marketing'
    | '/memory'
    | '/packages'
    | '/pipeline'
    | '/pixieset'
    | '/prep'
    | '/privacy'
    | '/quote'
    | '/reports'
    | '/reviews'
    | '/safety'
    | '/sops'
    | '/tasks'
    | '/team'
    | '/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/clients'
    | '/editing'
    | '/governance'
    | '/heirloom'
    | '/kpi'
    | '/leads'
    | '/marketing'
    | '/memory'
    | '/packages'
    | '/pipeline'
    | '/pixieset'
    | '/prep'
    | '/privacy'
    | '/quote'
    | '/reports'
    | '/reviews'
    | '/safety'
    | '/sops'
    | '/tasks'
    | '/team'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/clients'
    | '/editing'
    | '/governance'
    | '/heirloom'
    | '/kpi'
    | '/leads'
    | '/marketing'
    | '/memory'
    | '/packages'
    | '/pipeline'
    | '/pixieset'
    | '/prep'
    | '/privacy'
    | '/quote'
    | '/reports'
    | '/reviews'
    | '/safety'
    | '/sops'
    | '/tasks'
    | '/team'
    | '/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  ClientsRoute: typeof ClientsRoute
  EditingRoute: typeof EditingRoute
  GovernanceRoute: typeof GovernanceRoute
  HeirloomRoute: typeof HeirloomRoute
  KpiRoute: typeof KpiRoute
  LeadsRoute: typeof LeadsRoute
  MarketingRoute: typeof MarketingRoute
  MemoryRoute: typeof MemoryRoute
  PackagesRoute: typeof PackagesRoute
  PipelineRoute: typeof PipelineRoute
  PixiesetRoute: typeof PixiesetRoute
  PrepRoute: typeof PrepRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReportsRoute: typeof ReportsRoute
  ReviewsRoute: typeof ReviewsRoute
  SafetyRoute: typeof SafetyRoute
  SopsRoute: typeof SopsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops': {
      id: '/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof SopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pixieset': {
      id: '/pixieset'
      path: '/pixieset'
      fullPath: '/pixieset'
      preLoaderRoute: typeof PixiesetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heirloom': {
      id: '/heirloom'
      path: '/heirloom'
      fullPath: '/heirloom'
      preLoaderRoute: typeof HeirloomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  ClientsRoute: ClientsRoute,
  EditingRoute: EditingRoute,
  GovernanceRoute: GovernanceRoute,
  HeirloomRoute: HeirloomRoute,
  KpiRoute: KpiRoute,
  LeadsRoute: LeadsRoute,
  MarketingRoute: MarketingRoute,
  MemoryRoute: MemoryRoute,
  PackagesRoute: PackagesRoute,
  PipelineRoute: PipelineRoute,
  PixiesetRoute: PixiesetRoute,
  PrepRoute: PrepRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReportsRoute: ReportsRoute,
  ReviewsRoute: ReviewsRoute,
  SafetyRoute: SafetyRoute,
  SopsRoute: SopsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  WhatsappRoute: WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
